// Solana OCMS message-signing KAT generator (run manually):
//
//   cargo test -p ledger-sol-core --test kat_gen -- --ignored --nocapture
//
// Emits the canonical Solana off-chain-message vector (frozen into
// test-vectors/solana-message-signing-kat.json, asserted by the Rust core + iOS
// + Android). Solana is ed25519, so there is no external recoverable-signature
// reference like Tron's WalletCore vector; the cross-implementation contract is
// the three Maknoon impls (software + Ledger + Trezor) agreeing on the same
// envelope, validated on-device. This generator derives the SLIP-0010 ed25519
// secret at m/44'/501'/0'/0' from the standard BIP-39 test seed (the same path
// WalletCore + the Android SolanaPrimitives derive) and signs the OCMS envelope.
// Solana is mainnet-only.

use hmac::{Hmac, Mac};
use ledger_sol_core::sol_sign_message;
use sha2::Sha512;

const TEST_MNEMONIC: &str = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";
const TEST_SEED_HEX: &str = "5eb00bbddcf069084889a8ab9155568165f5c453ccb85e70811aaed6f6da5fc19a5ac40b389cd370d086206dec8aa6c43daea6690f20ad3d8d48b2d2ce9e38e4";
const SOL_PATH: &str = "m/44'/501'/0'/0'";
const SOL_MESSAGE: &str = "Maknoon Solana OCMS KAT v1";

// SLIP-0010 ed25519: HMAC-SHA512("ed25519 seed", seed) for the master, then
// hardened-only CKD (every Solana path component is hardened).
fn slip10_ed25519_secret(seed: &[u8], path: &[u32]) -> [u8; 32] {
    let mut mac = Hmac::<Sha512>::new_from_slice(b"ed25519 seed").unwrap();
    mac.update(seed);
    let i = mac.finalize().into_bytes();
    let mut key = [0u8; 32];
    let mut chain = [0u8; 32];
    key.copy_from_slice(&i[..32]);
    chain.copy_from_slice(&i[32..]);
    for &index in path {
        let hardened = index | 0x8000_0000;
        let mut mac = Hmac::<Sha512>::new_from_slice(&chain).unwrap();
        mac.update(&[0u8]); // 0x00 || key for hardened
        mac.update(&key);
        mac.update(&hardened.to_be_bytes());
        let i = mac.finalize().into_bytes();
        key.copy_from_slice(&i[..32]);
        chain.copy_from_slice(&i[32..]);
    }
    key
}

#[test]
#[ignore]
fn generate_solana_kat_vector() {
    let seed = hex::decode(TEST_SEED_HEX).unwrap();
    // m/44'/501'/0'/0' — all hardened.
    let secret = slip10_ed25519_secret(&seed, &[44, 501, 0, 0]);
    let signed = sol_sign_message(secret.to_vec(), SOL_MESSAGE.to_string()).unwrap();

    let corpus = serde_json::json!({
        "_comment": "Canonical Solana off-chain-message (OCMS, SIMD-0048) KAT. Generated by ledger-sol-core/tests/kat_gen.rs. ed25519, mainnet only. Asserted byte-for-byte by the Rust core, iOS, and Android; the on-device software==Ledger==Trezor match is the cross-impl gate. address = base58 ed25519 pubkey; signature = base58 64-byte ed25519 sig.",
        "mnemonic": TEST_MNEMONIC,
        "seedHex": TEST_SEED_HEX,
        "solana": {
            "path": SOL_PATH,
            "secretKeyHex": hex::encode(secret),
            "message": SOL_MESSAGE,
            "expectedAddress": signed.address,
            "expectedSignature": signed.signature
        }
    });
    println!("KAT_JSON_BEGIN");
    println!("{}", serde_json::to_string_pretty(&corpus).unwrap());
    println!("KAT_JSON_END");
}
